---
title: "Normas  para los componentes del coro"
lang: es
toc: false
---

Cantar polifonía con un grupo de gente puede ser una experiencia fascinante e inolvidable. Pero como cualquier actividad en equipo, participar en un coro requiere cierto grado de compromiso con el resto del grupo. Por esto queremos exponer brevemente lo que esperamos de nuestros miembros, para optimizar el rendimiento de los ensayos y conseguir buenos resultados en los conciertos:

## Normas de obligado cumplimiento para los miembros del coro de la Facultad de Ciencias

(Acuerdos tomados en reunión de 16-IV-2015 de Junta Directiva, Director y Jefes de Cuerda)

Todos los miembros del Coro deberán comprometerse a cumplir las normas que a continuación se enumeran. Aquellos miembros que piensen que razonablemente no pueden o no quieren cumplir con este compromiso deberán autoexcluirse de inmediato comunicándolo a la Junta Directiva; los restantes se entiende que aceptan el compromiso y la posibilidad de que sean dados de baja de no cumplirlo. Se pueden considerar excepciones muy justificadas a juicio del Director y bajas temporales que deberán comunicarse igualmente a la Junta Directiva.

- Asistir a un mínimo del 80% de las horas dedicadas a ensayos y conciertos, lo que será controlado diariamente por los Jefes de cuerda.
 
- Trabajar y preparar las partituras en casa, para que los ensayos puedan dedicarse a resolver dudas, matizar y empastar.
 
- Leer los mensajes remitidos por el Director, Junta Directiva o Jefes de Cuerda, siguiendo sus indicaciones sobre la marcha del coro.
 
- Estar informados, a través de la web del coro, sobre el repertorio que se esté trabajando en cada momento y las actuaciones próximas.
 
- Imprimir y llevar a los ensayos todas las partituras que se estén trabajando.
  
- Ser puntuales en acudir a los ensayos, de modo que éstos puedan comenzar a su hora y se aproveche el necesario calentamiento.
 
- Estar atentos en los ensayos a las indicaciones del Director, incluso cuando éste esté trabajando con una o varias cuerdas diferentes, evitando en lo posible comentarios sottovoce, consultas al móvil y otras actividades de distracción propia y ajena. 
  
- Respetar las orientaciones sobre vestuario y estilo para los conciertos, así como las normas de comportamiento básicas, especialmente en centros religiosos o ante personalidades de especial relevancia. 
 
- Conservar y cuidar el material cedido para las actuaciones (carpetas, pegatinas, pines, pañuelos, corbatas, etc.).

- Los Jefes de cuerda serán responsables de supervisar el cumplimiento de las normas por parte de los miembros de su sección, y tomarán parte, junto al Director, en la decisión de dar de baja a alguno de ellos si fuera necesario por el bien del coro.

Los jefes de cuerda en este momento son:

- **Sopranos**: Flor
- **Contraltos**: Maquica
- **Tenores**: Byrt
- **Bajos**: Ángel 